### ISSUE TITLE
Name of your repo

### ISSUE THREAD

**Issue by jorgicio** [Jannis234/jm-overlay#1]
Hi! Thanks for the overlay. However, everytime I sync the mirrors and overlays, your layout.conf gives a warning. Your repo is named jm-overlay, but appears as "dotnet" in your layout.conf. Please, fix it.

Thank you.

PS: The warning:
`Unavailable repository 'dotnet' referenced by masters entry in '/var/lib/layman/jm-overlay/metadata/layout.conf'
`

**Comment by Jannis234** [comment]
Thanks for using the overlay!
The repo's name is correct (it's stored in "profiles/repo_name", not layout.conf), but my layout.conf is referencing the "dotnet" overlay in the "masters" entry because I have ebuilds that depend on packages from that overlay (it silences warnings from repoman and avoids "dependency not found" problems).
You can fix the warning by adding the missing overlay (layman -a dotnet), but it should be safe to ignore it if you're not using the affected ebuilds.

**Comment by jorgicio** [comment]
Ok, got it. Thank you!
