### ISSUE TITLE
Contributing node modules

### ISSUE THREAD

**Issue by sjnewbury** [Jannis234/jm-overlay#12]
I'm using your overlay to port gtop (graphical system monitor for the Linux console) to Gentoo since you seem to have the most current and comprehensive nodejs infrastructure.

I'm not really familiar with nodejs, but I think I've figured out most of what I need to know.  Some questions though:

The package.json file in various projects lists dependencies including versions, sometimes minimum version, sometimes approximate version, and sometimes explicit version.  Your ebuild only supports the last case, I'm not sure how much it matters but have you considered any approach to dealing with the fuzzier requirements?

I'm not a huge fan of the contemporary philosophy of forking packages to provide known local static dependencies but it seems to be something that is standard procedure for nodejs projects which is why I guess you've gone the route of SLOTting and symlinking based on the version requirement.  How much leeway is there in the version requirements anyway, and would it sometimes be better to patch in support for newer versions of components where a package wants a really old release of something?  If doing so, is it best to patch the package.json file?

Finally, is there any plan to get your eclass and ebuilds into the main Gentoo portage repo?

**Comment by Jannis234** [comment]
> The package.json file in various projects lists dependencies including versions, sometimes minimum version, sometimes approximate version, and sometimes explicit version. Your ebuild only supports the last case, I'm not sure how much it matters but have you considered any approach to dealing with the fuzzier requirements?

I've tried doing that but there are a few problems: The ranges of supported versions of different packages overlap in some cases (Package A wants version 1.x of package C while package B wants 1.1.X and package D wants 1.2.X) which makes it difficult to pick the correct SLOT for each version. And since there is no consistent naming scheme across different packages, you can't tell the SLOT just by looking at the version number. That would make it a lot of work to implement this and if you keep in mind the amount of packages in a typical node dependency tree, that simply is too much work.

> I'm not a huge fan of the contemporary philosophy of forking packages to provide known local static dependencies but it seems to be something that is standard procedure for nodejs projects which is why I guess you've gone the route of SLOTting and symlinking based on the version requirement. How much leeway is there in the version requirements anyway, and would it sometimes be better to patch in support for newer versions of components where a package wants a really old release of something? If doing so, is it best to patch the package.json file?

Again, this depends on the package since the node ecosystem has no real rules/common practice for selecting dependencies. Many packages have no problem when running with different versions, but there are cases where packages changed their API and updating would cause breakage. If you wanted to do this, you'd have to carefully test each package to make sure nothing broke. Again, way too much work in my opinion.

> Finally, is there any plan to get your eclass and ebuilds into the main Gentoo portage repo?

Not really. I still think it's a bit too experimental for that.
